### ISSUE TITLE
Unable to find video files in folder

### ISSUE THREAD

**Issue by livgas** [vipoo/iRacingReplayOverlay.net#88]
Hey Guys Hope Someone Can Help, Iv tried to capture a replay and it keeps failing beacuse 
Unable to find video files in folder

2016-05-16T19:18:17 DEBUG: 00:13:13.5300000 Camera: Driver: Scott Death2, GroupNumber: 12, Number: 10, State: 81, GroupName: TV2, Name: CamTV2_09
2016-05-16T19:18:21 DEBUG: 00:13:17.5300000 Camera: Driver: Scott Death2, GroupNumber: 12, Number: 11, State: 81, GroupName: TV2, Name: CamTV2_10
2016-05-16T19:18:22 DEBUG: Setting Changed: key: , name: lastVideoFile, value: D:\Documents\iRacing\replay\unknown_capture-2016-05-15-22-59-22.replayscript
2016-05-16T19:18:25 DEBUG: 00:13:21.5300000 Camera: Driver: Scott Death2, GroupNumber: 12, Number: 1, State: 81, GroupName: TV2, Name: CamTV2_00
2016-05-16T19:18:27 DEBUG: Setting Changed: key: , name: lastVideoFile, value: D:\Documents\iRacing\replay\unknown_capture-2016-05-15-22-59-22.replayscript
2016-05-16T19:18:29 DEBUG: 00:13:25.5300000 Camera: Driver: Scott Death2, GroupNumber: 12, Number: 1, State: 81, GroupName: TV2, Name: CamTV2_00
2016-05-16T19:18:30 DEBUG: 00:13:26.5670000: Condition met
2016-05-16T19:18:30 INFO: 00:13:26.8430000 Scott Death2 finished in 3rd
2016-05-16T19:18:30 INFO: 00:13:26.8430000 Mark show results flash card.
2016-05-16T19:18:32 DEBUG: 00:13:28.5670000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.5830000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.6000000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.6170000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.6330000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.6470000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.6630000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: Setting Changed: key: , name: lastVideoFile, value: D:\Documents\iRacing\replay\unknown_capture-2016-05-15-22-59-22.replayscript
2016-05-16T19:18:32 DEBUG: 00:13:28.6800000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.6970000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.7130000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.7300000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.7470000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.7630000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.7770000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.7930000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.8100000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.8270000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.8430000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.8600000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.8770000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.8930000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.9170000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.9330000 Found no more finishers.
2016-05-16T19:18:32 DEBUG: 00:13:28.9500000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:28.9670000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:28.9830000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.0170000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.0330000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.0470000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.0630000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.0800000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.0970000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.1130000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.1300000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.1470000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.1630000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.1770000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.1930000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.2100000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.2270000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.2430000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.2600000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.2770000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.2930000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.3170000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.3330000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.3500000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.3670000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.3830000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.4000000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.4170000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.4330000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.4470000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.4630000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.4800000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.4970000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.5130000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.5300000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.5300000 Camera: Driver: Scott Death2, GroupNumber: 12, Number: 1, State: 81, GroupName: TV2, Name: CamTV2_00
2016-05-16T19:18:33 DEBUG: 00:13:29.5470000 Found no more finishers.
2016-05-16T19:18:33 DEBUG: 00:13:29.5630000 Found no more finishers.
2016-05-16T19:18:33 INFO: Sending key event ALT+F9
2016-05-16T19:18:37 INFO: Unable to find video files in folder 'D:\Documents\iRacing\replay' - check your Video Working folder
2016-05-16T19:18:37 Saving overlay data to D:\Documents\iRacing\replay/unknown_capture-2016-05-16-19-18-37.replayscript
2016-05-16T19:18:37 DEBUG: Setting Changed: key: , name: lastVideoFile, value: D:\Documents\iRacing\replay\unknown_capture-2016-05-15-22-59-22.replayscript
2016-05-16T19:18:37 INFO: Setting speed to 0
2016-05-16T19:18:38 ERROR: Unable to find video files in 'D:\Documents\iRacing\replay' - possible wrong working folder
2016-05-16T19:18:38 ERROR:    at iRacingReplayOverlay.Phases.IRacingReplay._CaptureRaceTest(Action`1 onComplete, IEnumerable`1 samples) in C:\projects\iracingreplayoverlay-net-bdpnd\Phases\CaptureRace.cs:line 128
   at iRacingReplayOverlay.Phases.IRacingReplay._CaptureRace(Action`1 onComplete) in C:\projects\iracingreplayoverlay-net-bdpnd\Phases\CaptureRace.cs:line 53
   at iRacingReplayOverlay.Phases.IRacingReplay.<CaptureRace>b__31_0(Action`1 a) in C:\projects\iracingreplayoverlay-net-bdpnd\Phases\IRacingReplay.cs:line 98
   at iRacingReplayOverlay.Phases.IRacingReplay.<>c__DisplayClass26_0.<Add>b__0() in C:\projects\iracingreplayoverlay-net-bdpnd\Phases\IRacingReplay.cs:line 66
   at iRacingReplayOverlay.Phases.IRacingReplay.<>c__DisplayClass42_0.<InTheBackground>b__0() in C:\projects\iracingreplayoverlay-net-bdpnd\Phases\IRacingReplay.cs:line 167
2016-05-16T19:18:38 INFO: Process aborted
2016-05-16T19:18:38 DEBUG: Setting Changed: key: , name: WorkingFolder, value: D:\Documents\iRacing\replay
2016-05-16T19:18:38 INFO: Moving logging to file D:\Documents\iRacing\replay\general.log

**Comment by livgas** [comment]
2016-05-16T19:18:38	----------------------------
2016-05-16T19:18:38	INFO: Moving logging to file D:\Documents\iRacing\replay\general.log
2016-05-16T19:18:42	DEBUG: Setting Changed: key: , name: lastVideoFile, value: D:\Documents\iRacing\replay\unknown_capture-2016-05-15-22-59-22.replayscript
2016-05-16T19:18:49
2016-05-16T22:15:42	----------------------------
2016-05-16T22:15:42	DEBUG: Local user config path: C:\Users\Scott\AppData\Local\iRacingReplayOverlay\iRacingReplayOverlay.exe_Url_txm2g20qpesavwaqbrk5ulnzi2blkchw\1.0.3.58\user.config
2016-05-16T22:15:42	DEBUG: Setting Changed: key: , name: lastVideoFile, value: D:\Documents\iRacing\replay\unknown_capture-2016-05-15-22-59-22.replayscript
2016-05-16T22:15:42	DEBUG: Application Version: 1.0.3.58
2016-05-16T22:15:42	DEBUG: OS: 64x
2016-05-16T22:15:42	DEBUG: ProcessorCount:  8
2016-05-16T22:15:42	DEBUG: Drive: C:\, Type: Fixed, Format: NTFS, Size: 119507251200, AvailableFreeSpace: 71413751808
2016-05-16T22:15:42	DEBUG: Drive: D:\, Type: Fixed, Format: NTFS, Size: 1000202039296, AvailableFreeSpace: 370242080768
2016-05-16T22:15:42	DEBUG: Drive: F:\, Type: CDRom, Format: , Size: , AvailableFreeSpace: 
2016-05-16T22:15:42	DEBUG: SystemPageSize:  4096
2016-05-16T22:15:42	DEBUG: Version:  4.0.30319.42000
2016-05-16T22:15:42	INFO: Waiting to connect to iRacing application
2016-05-16T22:15:43	DEBUG: AddressWidth: 64
2016-05-16T22:15:43	DEBUG: Architecture: 9
2016-05-16T22:15:43	DEBUG: AssetTag: To Be Filled By O.E.M.
2016-05-16T22:15:43	DEBUG: Availability: 3
2016-05-16T22:15:43	DEBUG: Caption: AMD64 Family 21 Model 2 Stepping 0
2016-05-16T22:15:43	DEBUG: Characteristics: 
2016-05-16T22:15:43	DEBUG: ConfigManagerErrorCode: 
2016-05-16T22:15:43	DEBUG: ConfigManagerUserConfig: 
2016-05-16T22:15:43	DEBUG: CpuStatus: 1
2016-05-16T22:15:43	DEBUG: CreationClassName: Win32_Processor
2016-05-16T22:15:43	DEBUG: CurrentClockSpeed: 4000
2016-05-16T22:15:43	DEBUG: CurrentVoltage: 11
2016-05-16T22:15:43	DEBUG: DataWidth: 64
2016-05-16T22:15:43	DEBUG: Description: AMD64 Family 21 Model 2 Stepping 0
2016-05-16T22:15:43	DEBUG: DeviceID: CPU0
2016-05-16T22:15:43	DEBUG: ErrorCleared: 
2016-05-16T22:15:43	DEBUG: ErrorDescription: 
2016-05-16T22:15:43	DEBUG: ExtClock: 200
2016-05-16T22:15:43	DEBUG: Family: 2
2016-05-16T22:15:43	DEBUG: InstallDate: 
2016-05-16T22:15:43	DEBUG: L2CacheSize: 8192
2016-05-16T22:15:43	DEBUG: L2CacheSpeed: 
2016-05-16T22:15:43	DEBUG: L3CacheSize: 8192
2016-05-16T22:15:43	DEBUG: L3CacheSpeed: 0
2016-05-16T22:15:43	DEBUG: LastErrorCode: 
2016-05-16T22:15:43	DEBUG: Level: 21
2016-05-16T22:15:43	DEBUG: LoadPercentage: 15
2016-05-16T22:15:43	DEBUG: Manufacturer: AuthenticAMD
2016-05-16T22:15:43	DEBUG: MaxClockSpeed: 4000
2016-05-16T22:15:43	DEBUG: Name: AMD FX-8320E Eight-Core Processor              
2016-05-16T22:15:43	DEBUG: NumberOfCores: 4
2016-05-16T22:15:43	DEBUG: NumberOfEnabledCore: 8
2016-05-16T22:15:43	DEBUG: NumberOfLogicalProcessors: 8
2016-05-16T22:15:43	DEBUG: OtherFamilyDescription: 
2016-05-16T22:15:43	DEBUG: PartNumber: To Be Filled By O.E.M.
2016-05-16T22:15:43	DEBUG: PNPDeviceID: 
2016-05-16T22:15:43	DEBUG: PowerManagementCapabilities: 
2016-05-16T22:15:43	DEBUG: PowerManagementSupported: False
2016-05-16T22:15:43	DEBUG: ProcessorId: 178BFBFF00600F20
2016-05-16T22:15:43	DEBUG: ProcessorType: 3
2016-05-16T22:15:43	DEBUG: Revision: 512
2016-05-16T22:15:43	DEBUG: Role: CPU
2016-05-16T22:15:43	DEBUG: SecondLevelAddressTranslationExtensions: True
2016-05-16T22:15:43	DEBUG: SerialNumber: To Be Filled By O.E.M.
2016-05-16T22:15:43	DEBUG: SocketDesignation: AM3R2
2016-05-16T22:15:43	DEBUG: Status: OK
2016-05-16T22:15:43	DEBUG: StatusInfo: 3
2016-05-16T22:15:43	DEBUG: Stepping: 0
2016-05-16T22:15:43	DEBUG: SystemCreationClassName: Win32_ComputerSystem
2016-05-16T22:15:43	DEBUG: SystemName: DESKTOP-MCSPJCF
2016-05-16T22:15:43	DEBUG: ThreadCount: 8
2016-05-16T22:15:43	DEBUG: UniqueId: 
2016-05-16T22:15:43	DEBUG: UpgradeMethod: 27
2016-05-16T22:15:43	DEBUG: Version: Model 2, Stepping 0
2016-05-16T22:15:43	DEBUG: VirtualizationFirmwareEnabled: False
2016-05-16T22:15:43	DEBUG: VMMonitorModeExtensions: True
2016-05-16T22:15:43	DEBUG: VoltageCaps: 
2016-05-16T22:15:43	DEBUG: AcceleratorCapabilities: 
2016-05-16T22:15:43	DEBUG: AdapterCompatibility: NVIDIA
2016-05-16T22:15:43	DEBUG: AdapterDACType: Integrated RAMDAC
2016-05-16T22:15:43	DEBUG: AdapterRAM: 1073741824
2016-05-16T22:15:43	DEBUG: Availability: 3
2016-05-16T22:15:43	DEBUG: CapabilityDescriptions: 
2016-05-16T22:15:43	DEBUG: Caption: NVIDIA GeForce GTX 750
2016-05-16T22:15:43	DEBUG: ColorTableEntries: 
2016-05-16T22:15:43	DEBUG: ConfigManagerErrorCode: 0
2016-05-16T22:15:43	DEBUG: ConfigManagerUserConfig: False
2016-05-16T22:15:43	DEBUG: CreationClassName: Win32_VideoController
2016-05-16T22:15:43	DEBUG: CurrentBitsPerPixel: 32
2016-05-16T22:15:43	DEBUG: CurrentHorizontalResolution: 1920
2016-05-16T22:15:43	DEBUG: CurrentNumberOfColors: 4294967296
2016-05-16T22:15:43	DEBUG: CurrentNumberOfColumns: 0
2016-05-16T22:15:43	DEBUG: CurrentNumberOfRows: 0
2016-05-16T22:15:43	DEBUG: CurrentRefreshRate: 60
2016-05-16T22:15:43	DEBUG: CurrentScanMode: 4
2016-05-16T22:15:43	DEBUG: CurrentVerticalResolution: 1080
2016-05-16T22:15:43	DEBUG: Description: NVIDIA GeForce GTX 750
2016-05-16T22:15:43	DEBUG: DeviceID: VideoController1
2016-05-16T22:15:43	DEBUG: DeviceSpecificPens: 
2016-05-16T22:15:43	DEBUG: DitherType: 0
2016-05-16T22:15:43	DEBUG: DriverDate: 20160427000000.000000-000
2016-05-16T22:15:43	DEBUG: DriverVersion: 10.18.13.6510
2016-05-16T22:15:43	DEBUG: ErrorCleared: 
2016-05-16T22:15:43	DEBUG: ErrorDescription: 
2016-05-16T22:15:43	DEBUG: ICMIntent: 
2016-05-16T22:15:43	DEBUG: ICMMethod: 
2016-05-16T22:15:43	DEBUG: InfFilename: oem13.inf
2016-05-16T22:15:43	DEBUG: InfSection: Section038
2016-05-16T22:15:43	DEBUG: InstallDate: 
2016-05-16T22:15:43	DEBUG: InstalledDisplayDrivers: nvd3dumx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvd3dum,nvwgf2um,nvwgf2um,nvwgf2um
2016-05-16T22:15:43	DEBUG: LastErrorCode: 
2016-05-16T22:15:43	DEBUG: MaxMemorySupported: 
2016-05-16T22:15:43	DEBUG: MaxNumberControlled: 
2016-05-16T22:15:43	DEBUG: MaxRefreshRate: 75
2016-05-16T22:15:43	DEBUG: MinRefreshRate: 23
2016-05-16T22:15:43	DEBUG: Monochrome: False
2016-05-16T22:15:43	DEBUG: Name: NVIDIA GeForce GTX 750
2016-05-16T22:15:43	DEBUG: NumberOfColorPlanes: 
2016-05-16T22:15:43	DEBUG: NumberOfVideoPages: 
2016-05-16T22:15:43	DEBUG: PNPDeviceID: PCI\VEN_10DE&DEV_1381&SUBSYS_84AD1043&REV_A2\4&2A1FC852&0&0010
2016-05-16T22:15:43	DEBUG: PowerManagementCapabilities: 
2016-05-16T22:15:43	DEBUG: PowerManagementSupported: 
2016-05-16T22:15:43	DEBUG: ProtocolSupported: 
2016-05-16T22:15:43	DEBUG: ReservedSystemPaletteEntries: 
2016-05-16T22:15:43	DEBUG: SpecificationVersion: 
2016-05-16T22:15:43	DEBUG: Status: OK
2016-05-16T22:15:43	DEBUG: StatusInfo: 
2016-05-16T22:15:43	DEBUG: SystemCreationClassName: Win32_ComputerSystem
2016-05-16T22:15:43	DEBUG: SystemName: DESKTOP-MCSPJCF
2016-05-16T22:15:43	DEBUG: SystemPaletteEntries: 
2016-05-16T22:15:43	DEBUG: TimeOfLastReset: 
2016-05-16T22:15:43	DEBUG: VideoArchitecture: 5
2016-05-16T22:15:43	DEBUG: VideoMemoryType: 2
2016-05-16T22:15:43	DEBUG: VideoMode: 
2016-05-16T22:15:43	DEBUG: VideoModeDescription: 1920 x 1080 x 4294967296 colors
2016-05-16T22:15:43	DEBUG: VideoProcessor: GeForce GTX 750
2016-05-16T22:15:43	DEBUG: Setting Changed: key: , name: GitHubCachedReleases, value: GitHubReleases.GitHubCachedReleases[]
2016-05-16T22:15:47	DEBUG: Setting Changed: key: , name: lastVideoFile, value: D:\Documents\iRacing\replay\unknown_capture-2016-05-15-22-59-22.replayscript
2016-05-16T22:16:07	DEBUG: Setting Changed: key: , name: lastVideoFile, value: D:\Documents\iRacing\replay\unknown_capture-2016-05-15-22-59-22.replayscript
2016-05-16T22:16:27	DEBUG: Setting Changed: key: , name: lastVideoFile, value: D:\Documents\iRacing\replay\unknown_capture-2016-05-15-22-59-22.replayscript
2016-05-16T22:16:332016-05-16T22:16:33

**Comment by dnetherton** [comment]
What video capture program are u using?  Its important to remember that this application does not do the actual video capture, only control cameras in iracing, and then edit the video file.

It needs a capture program, such as Bandicam, OBS, or Nvidia Shadowplay.  On the iracing forum post, there is a pdf attachment that walks thru using the application with OBS.

Things to check:

1: Make sure your video capture program actually did record a video?
2: Note the folder that the video was stored in
3: Make sure iRacing Replay Director has this folder entered in the main window - so it knows where to find the videos.
2: Make sure your video capture software is configured to respond to ALT+F9 - this is so my application can trigger the start and stop of capturing.

Tips:
1: Use the 'verify video capture' button to test the process.

**Comment by livgas** [comment]
Ok I understand. No im not running any capture program so will try obs tonight.
