### ISSUE TITLE
Error with video conversion

### ISSUE THREAD

**Issue by LaundroMat** [vipoo/iRacingReplayOverlay.net#96]
I captured a replay through iRacingReplayDirector with OBS. When starting the conversion, I see this error

![image](https://cloud.githubusercontent.com/assets/42320/25781970/5fd9f1d6-3341-11e7-9d75-105c88194532.png)

I then tried to verify the video:

![image](https://cloud.githubusercontent.com/assets/42320/25781972/780763ec-3341-11e7-944b-e3a5b425c43a.png)

This is the last part of the log file:

```
2017-05-07T15:56:53	----------------------------
2017-05-07T15:56:53	INFO: Moving logging to file C:\Users\Mathieu\Videos\iRacing\general.log
2017-05-07T15:56:58	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T15:57:19	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T15:57:40	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T15:58:01	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T15:58:21	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T15:58:42	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T15:58:52	ERROR: The requested attribute was not found.
2017-05-07T15:58:52	ERROR:    at MediaFoundation.Misc.MFError.ThrowExceptionForHR(Int32 hr) in C:\projects\supermflib\mfnet\mflib\src\MFUtils.cs:line 2578
   at MediaFoundation.Net.HrExtension.Hr(Int32 hr) in C:\projects\supermflib\SuperMFLib\HrExtension.cs:line 27
   at MediaFoundation.Net.MediaType.GetInt(Guid guid) in C:\projects\supermflib\SuperMFLib\MediaType.cs:line 191
   at MediaFoundation.Net.MediaType.get_AudioNumberOfChannels() in C:\projects\supermflib\SuperMFLib\MediaType.cs:line 91
   at iRacingReplayOverlay.Video.VideoAttributes.TestFor(String videoFileName) in C:\projects\iracingreplayoverlay-net-bdpnd\Video\Attributes.cs:line 87
   at iRacingReplayOverlay.TestVideoConversion.TranscodeVideoTest(String filename) in C:\projects\iracingreplayoverlay-net-bdpnd\TestVideoConversion.cs:line 118
   at iRacingReplayOverlay.TestVideoConversion.RunTest(String filename, SynchronizationContext context) in C:\projects\iracingreplayoverlay-net-bdpnd\TestVideoConversion.cs:line 99
2017-05-07T15:58:53	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T15:59:14	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T15:59:34	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T15:59:55	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:00:16	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:00:37	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:00:58	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:01:19	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:01:40	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:02:01	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:02:22	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:02:43	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:03:04	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:03:12	ERROR: The requested attribute was not found.
2017-05-07T16:03:12	ERROR:    at MediaFoundation.Misc.MFError.ThrowExceptionForHR(Int32 hr) in C:\projects\supermflib\mfnet\mflib\src\MFUtils.cs:line 2578
   at MediaFoundation.Net.HrExtension.Hr(Int32 hr) in C:\projects\supermflib\SuperMFLib\HrExtension.cs:line 27
   at MediaFoundation.Net.MediaType.GetInt(Guid guid) in C:\projects\supermflib\SuperMFLib\MediaType.cs:line 191
   at MediaFoundation.Net.MediaType.get_AudioNumberOfChannels() in C:\projects\supermflib\SuperMFLib\MediaType.cs:line 91
   at iRacingReplayOverlay.Video.VideoAttributes.TestFor(String videoFileName) in C:\projects\iracingreplayoverlay-net-bdpnd\Video\Attributes.cs:line 87
   at iRacingReplayOverlay.TestVideoConversion.TranscodeVideoTest(String filename) in C:\projects\iracingreplayoverlay-net-bdpnd\TestVideoConversion.cs:line 118
   at iRacingReplayOverlay.TestVideoConversion.RunTest(String filename, SynchronizationContext context) in C:\projects\iracingreplayoverlay-net-bdpnd\TestVideoConversion.cs:line 99
2017-05-07T16:03:14	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:03:21	ERROR: The requested attribute was not found.
2017-05-07T16:03:21	ERROR:    at MediaFoundation.Misc.MFError.ThrowExceptionForHR(Int32 hr) in C:\projects\supermflib\mfnet\mflib\src\MFUtils.cs:line 2578
   at MediaFoundation.Net.HrExtension.Hr(Int32 hr) in C:\projects\supermflib\SuperMFLib\HrExtension.cs:line 27
   at MediaFoundation.Net.MediaType.GetInt(Guid guid) in C:\projects\supermflib\SuperMFLib\MediaType.cs:line 191
   at MediaFoundation.Net.MediaType.get_AudioNumberOfChannels() in C:\projects\supermflib\SuperMFLib\MediaType.cs:line 91
   at iRacingReplayOverlay.Video.VideoAttributes.TestFor(String videoFileName) in C:\projects\iracingreplayoverlay-net-bdpnd\Video\Attributes.cs:line 87
   at iRacingReplayOverlay.TestVideoConversion.TranscodeVideoTest(String filename) in C:\projects\iracingreplayoverlay-net-bdpnd\TestVideoConversion.cs:line 118
   at iRacingReplayOverlay.TestVideoConversion.RunTest(String filename, SynchronizationContext context) in C:\projects\iracingreplayoverlay-net-bdpnd\TestVideoConversion.cs:line 99
2017-05-07T16:03:25	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:03:35	ERROR: The requested attribute was not found.
2017-05-07T16:03:35	ERROR:    at MediaFoundation.Misc.MFError.ThrowExceptionForHR(Int32 hr) in C:\projects\supermflib\mfnet\mflib\src\MFUtils.cs:line 2578
   at MediaFoundation.Net.HrExtension.Hr(Int32 hr) in C:\projects\supermflib\SuperMFLib\HrExtension.cs:line 27
   at MediaFoundation.Net.MediaType.GetInt(Guid guid) in C:\projects\supermflib\SuperMFLib\MediaType.cs:line 191
   at MediaFoundation.Net.MediaType.get_AudioNumberOfChannels() in C:\projects\supermflib\SuperMFLib\MediaType.cs:line 91
   at iRacingReplayOverlay.Video.VideoAttributes.TestFor(String videoFileName) in C:\projects\iracingreplayoverlay-net-bdpnd\Video\Attributes.cs:line 87
   at iRacingReplayOverlay.TestVideoConversion.TranscodeVideoTest(String filename) in C:\projects\iracingreplayoverlay-net-bdpnd\TestVideoConversion.cs:line 118
   at iRacingReplayOverlay.TestVideoConversion.RunTest(String filename, SynchronizationContext context) in C:\projects\iracingreplayoverlay-net-bdpnd\TestVideoConversion.cs:line 99
2017-05-07T16:03:35	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:03:56	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:04:17	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:04:38	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:04:59	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:05:20	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:05:29	INFO: Moving logging to file C:\Users\Mathieu\Videos\iRacing\\capture.log

2017-05-07T16:10:44	----------------------------
2017-05-07T16:10:44	INFO: Moving logging to file C:\Users\Mathieu\Videos\iRacing\general.log
2017-05-07T16:10:49	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:11:10	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:11:31	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:11:51	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:12:12	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:12:33	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:12:54	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:13:14	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:13:35	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:13:56	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:14:17	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:14:38	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:14:58	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:15:19	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:15:40	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:16:01	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:16:21	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:16:42	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:17:03	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:17:24	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:17:45	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:18:05	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:18:26	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:18:39	DEBUG: Setting Changed: key: , name: videoBitRate, value: 9
2017-05-07T16:18:42	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1606-09.replayscript
2017-05-07T16:18:45	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:19:06	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:19:06	ERROR: The requested attribute was not found.
2017-05-07T16:19:06	ERROR:    at MediaFoundation.Misc.MFError.ThrowExceptionForHR(Int32 hr) in C:\projects\supermflib\mfnet\mflib\src\MFUtils.cs:line 2578
   at MediaFoundation.Net.HrExtension.Hr(Int32 hr) in C:\projects\supermflib\SuperMFLib\HrExtension.cs:line 27
   at MediaFoundation.Net.MediaType.GetInt(Guid guid) in C:\projects\supermflib\SuperMFLib\MediaType.cs:line 191
   at MediaFoundation.Net.MediaType.get_AudioNumberOfChannels() in C:\projects\supermflib\SuperMFLib\MediaType.cs:line 91
   at iRacingReplayOverlay.Video.VideoAttributes.TestFor(String videoFileName) in C:\projects\iracingreplayoverlay-net-bdpnd\Video\Attributes.cs:line 87
   at iRacingReplayOverlay.TestVideoConversion.TranscodeVideoTest(String filename) in C:\projects\iracingreplayoverlay-net-bdpnd\TestVideoConversion.cs:line 118
   at iRacingReplayOverlay.TestVideoConversion.RunTest(String filename, SynchronizationContext context) in C:\projects\iracingreplayoverlay-net-bdpnd\TestVideoConversion.cs:line 99
2017-05-07T16:19:11	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:19:32	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:19:53	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:20:14	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:20:35	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:20:55	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:21:16	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:21:37	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:21:58	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:22:19	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:22:40	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:23:01	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
2017-05-07T16:23:21	DEBUG: Setting Changed: key: , name: lastVideoFile, value: C:\Users\Mathieu\Videos\iRacing\2017-05-07-1556-49.replayscript
```

**Comment by LaundroMat** [comment]
Oh, found it. I had OBS saving the audio as MP3 while it should be set to AAC. Maybe the PDF should mention this too?
